name: Simple CI

on:
  push:
    branches:
      - talview_changes
      - develop
jobs:
  run-ci:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - run: npm install
    - run: npm run build
    - uses: actions/upload-artifact@v3
      with:
        name: lib-jitsi-meet-artifact
        path: |
          connection_optimization/
          dist/
          modules/browser/capabilities.json
          types/
          package.json

